github: [Repository metadata]
permalink: /blog/:year/:month/:day/:title/
navigation:
- title: Home
  url: /
- title: Projects
  url: /projects/
- title: Blog
  url: /blog/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
