github: [Repository metadata]
permalink: /blog/:year/:month/:day/:title/
title: Esther Makes Tech
url: http://esthermakes.tech
logo: https://media.githubusercontent.com/media/drejkim/drejkim.github.io/master/assets/brand-512.png
navigation:
- title: Home
  url: /
- title: About
  url: /about/
- title: Projects
  url: /projects/
- title: Blog
  url: /blog/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-seo-tag