github: [Repository metadata]
permalink: /blog/:year/:month/:day/:title/

# SEO
title: Esther Makes Tech
description: A collection of projects and writings by Esther Jun Kim
url: http://esthermakes.tech
logo: https://media.githubusercontent.com/media/estherjk/estherjk.github.io/master/assets/img/brand/brand-512.png
twitter:
  username: esthermakestech
  card: summary
social:
  name: Esther Jun Kim
  links:
    - https://twitter.com/esthermakestech
    - https://github.com/estherjk
    - https://www.linkedin.com/in/estherjunkim
defaults:
  - scope:
      path: ""
    values:
      image: https://media.githubusercontent.com/media/estherjk/estherjk.github.io/master/assets/img/brand/brand-og.png

navigation:
- title: Home
  url: /
- title: About
  url: /about/
- title: Projects
  url: /projects/
- title: Blog
  url: /blog/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-seo-tag