highlighter: pygments
github: [Repository metadata]
permalink: /blog/:year/:month/:day/:title
navigation:
- title: Bio
  url: /bio/
- title: Blog
  url: /blog/
blogCategories:
- category: edison
  title: Intel Edison
- category: mobile
  title: Mobile
- category: ux
  title: UX
- category: web
  title: Web Apps
