github: [Repository metadata]
permalink: /blog/:year/:month/:day/:title/
navigation:
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title: Projects
  url: /projects/
- title: Mentions
  url: /mentions/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
