github: [Repository metadata]
permalink: /blog/:year/:month/:day/:title
navigation:
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title: Projects
  url: /projects/
markdown: redcarpet
highlighter: pygments
